-- Lookup tables
CREATE TABLE Career (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

-- Core user tables
CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    user_type VARCHAR2(10) CHECK (user_type IN ('admin', 'student')) NOT NULL
);

-- Shared user profile
CREATE TABLE UserProfile (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    apellido_paterno VARCHAR2(50) NOT NULL,
    apellido_materno VARCHAR2(50),
    nombres VARCHAR2(100) NOT NULL,
    faculty_id NUMBER NOT NULL,
    campus_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

-- Students table
CREATE TABLE Students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    student_id VARCHAR2(20) UNIQUE NOT NULL,
    email VARCHAR2(100),
    cellphone VARCHAR2(20),
    house_phone VARCHAR2(20),
    career_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (career_id) REFERENCES Career(id)
);

-- Admins table
CREATE TABLE Admins (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

-- Combined application table
CREATE TABLE SocialServiceApplication (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Link to the student
    student_id NUMBER NOT NULL,
    FOREIGN KEY (student_id) REFERENCES Students(id),

    -- Personal Information (excluding name parts)
    fecha_nacimiento DATE,
    lugar_nacimiento VARCHAR2(100),
    sexo VARCHAR2(10),
    edad NUMBER,
    estado_civil VARCHAR2(20),

    -- Address
    calle VARCHAR2(100),
    numero VARCHAR2(20),
    colonia VARCHAR2(100),
    ciudad VARCHAR2(100),
    estado VARCHAR2(100),

    -- Contact Info
    telefono VARCHAR2(20),
    celular VARCHAR2(20),
    correo VARCHAR2(100),

    -- Academic Info
    carrera VARCHAR2(100),
    matricula VARCHAR2(20),
    semestre NUMBER,
    porcentaje_materias VARCHAR2(50),

    -- Institution Info
    institucion_nombre VARCHAR2(100),
    institucion_departamento VARCHAR2(100),
    institucion_calle VARCHAR2(100),
    institucion_numero VARCHAR2(20),
    institucion_colonia VARCHAR2(100),
    institucion_ciudad VARCHAR2(100),
    institucion_estado VARCHAR2(100),
    institucion_telefono VARCHAR2(20),
    institucion_celular VARCHAR2(20),

    -- Assignment Info
    zona VARCHAR2(10),
    horario VARCHAR2(100),
    modalidad VARCHAR2(30),
    platica_sensibilizacion VARCHAR2(3) CHECK (platica_sensibilizacion IN ('si', 'no')),

    -- System tracking
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    submitted_at DATE DEFAULT SYSDATE
);

CREATE TABLE SocialServiceProgress (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL UNIQUE,
    papeleria_entregada CHAR(1) DEFAULT 'N' CHECK (papeleria_entregada IN ('Y', 'N')),
    reportes_entregados CHAR(1) DEFAULT 'N' CHECK (reportes_entregados IN ('Y', 'N')),
    horas_completadas NUMBER DEFAULT 0,
    updated_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (student_id) REFERENCES Students(id)
);

INSERT INTO carrer (id, name) VALUES (1, 'Aeroespacial'),
INSERT INTO carrer (id, name) VALUES (2, 'Civil'),
INSERT INTO carrer (id, name) VALUES (3, 'Computacion'),
INSERT INTO carrer (id, name) VALUES (4, 'Minas y Metalurgia'),
INSERT INTO carrer (id, name) VALUES (5, 'Topografica'),
INSERT INTO carrer (id, name) VALUES (6, 'Procesos industriales'),
INSERT INTO carrer (id, name) VALUES (7, 'Fisica'),
INSERT INTO carrer (id, name) VALUES (8, 'Geologica'),
INSERT INTO carrer (id, name) VALUES (9, 'Ciencia de Datos y Matematicas aplicadas')

INSERT INTO Users (username, password, user_type) VALUES ('anaadm', 'admin123', 'admin');
INSERT INTO Users (username, password, user_type) VALUES ('luisadm', 'admin456', 'admin');
INSERT INTO Users (username, password, user_type) VALUES ('jose_gomez', 'pass001', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('maria_hernandez', 'pass002', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('carlos_lopez', 'pass003', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('laura_ruiz', 'pass004', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('fernando_diaz', 'pass005', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('sofia_fernandez', 'pass006', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('diego_ramirez', 'pass007', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('valeria_mendoza', 'pass008', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('david_ortiz', 'pass009', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('andrea_torres', 'pass010', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('hector_rojas', 'pass011', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('elena_castro', 'pass012', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('raul_martinez', 'pass013', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('natalia_vargas', 'pass014', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('sergio_soto', 'pass015', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('monica_guzman', 'pass016', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('jorge_sandoval', 'pass017', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('fatima_morales', 'pass018', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ricardo_salazar', 'pass019', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('karla_navarro', 'pass020', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('alejandro_rivera', 'pass021', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('diana_vega', 'pass022', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ivan_aguilar', 'pass023', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('isabel_campos', 'pass024', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('roberto_miranda', 'pass025', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('pamela_reyes', 'pass026', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('marco_ayala', 'pass027', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('alejandra_garza', 'pass028', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('adrian_pineda', 'pass029', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('melissa_luna', 'pass030', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('julio_carrillo', 'pass031', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('brenda_mendez', 'pass032', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('francisco_valdez', 'pass033', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('mariana_silva', 'pass034', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('gustavo_perez', 'pass035', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('rebeca_rios', 'pass036', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('tomas_quintero', 'pass037', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('irene_lozano', 'pass038', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('arturo_barajas', 'pass039', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('judith_molina', 'pass040', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ramiro_guerrero', 'pass041', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('paola_santos', 'pass042', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('edgar_tapia', 'pass043', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('gema_fuentes', 'pass044', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('bryan_cano', 'pass045', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('araceli_martel', 'pass046', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('lazaro_castillo', 'pass047', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('leticia_sierra', 'pass048', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('hugo_olivares', 'pass049', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ruth_saldana', 'pass050', 'student');

INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (1, 'Ana', 'Gonzalez', 'Salazar', 'admin'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (2, 'Luis', 'Rodriguez', 'Jaime', 'admin'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (3, 'Jose', 'Gomez', 'Salazar', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (4, 'Maria', 'Hernandez', 'Castaneda', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (5, 'Carlos', 'Lopez', 'Meza', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (6, 'Laura', 'Ruiz', 'Ayala', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (7, 'Fernando', 'Diaz', 'Camacho', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (8, 'Sofia', 'Fernandez', 'Rojas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (9, 'Diego', 'Ramirez', 'Cardenas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (10, 'Valeria', 'Mendoza', 'Pena', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (11, 'David', 'Ortiz', 'Paredes', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (12, 'Andrea', 'Torres', 'Barajas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (13, 'Hector', 'Rojas', 'Montoya', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (14, 'Elena', 'Castro', 'Escobar', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (15, 'Raul', 'Martinez', 'Vargas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (16, 'Natalia', 'Vargas', 'Guerrero', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (17, 'Sergio', 'Soto', 'Vazquez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (18, 'Monica', 'Guzman', 'Luna', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (19, 'Jorge', 'Sandoval', 'Bravo', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (20, 'Fatima', 'Morales', 'Molina', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (21, 'Ricardo', 'Salazar', 'Rivera', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (22, 'Karla', 'Navarro', 'Rodriguez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (23, 'Alejandro', 'Rivera', 'Tapia', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (24, 'Diana', 'Vega', 'Silva', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (25, 'Ivan', 'Aguilar', 'Lozano', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (26, 'Isabel', 'Campos', 'Soto', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (27, 'Roberto', 'Miranda', 'Gonzalez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (28, 'Pamela', 'Reyes', 'Carrillo', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (29, 'Marco', 'Ayala', 'Santos', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (30, 'Alejandra', 'Garza', 'Perez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (31, 'Adrian', 'Pineda', 'Ramirez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (32, 'Melissa', 'Luna', 'Cruz', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (33, 'Julio', 'Carrillo', 'Romero', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (34, 'Brenda', 'Mendez', 'Navarro', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (35, 'Francisco', 'Valdez', 'Fuentes', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (36, 'Mariana', 'Silva', 'Quintero', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (37, 'Gustavo', 'Perez', 'Guerrero', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (38, 'Rebeca', 'Rios', 'Sanchez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (39, 'Tomas', 'Quintero', 'Delgado', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (40, 'Irene', 'Lozano', 'Camacho', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (41, 'Arturo', 'Barajas', 'Gutierrez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (42, 'Judith', 'Molina', 'Sandoval', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (43, 'Ramiro', 'Guerrero', 'Lopez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (44, 'Paola', 'Santos', 'Vega', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (45, 'Edgar', 'Tapia', 'Morales', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (46, 'Gema', 'Fuentes', 'Herrera', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (47, 'Bryan', 'Cano', 'Rodriguez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (48, 'Araceli', 'Martel', 'Gonzalez', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (49, 'Lazaro', 'Castillo', 'Vargas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (50, 'Leticia', 'Sierra', 'Cardenas', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (51, 'Hugo', 'Olivares', 'Paredes', 'student'),
INSERT INTO UserProfile (id, nombre, apellido_paterno, apellido_materno, user_type) VALUES (52, 'Ruth', 'Saldana', 'Gonzalez', 'student');