-- Lookup tables
CREATE TABLE Campus (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE Faculty (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE Career (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE State (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE City (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    state_id NUMBER NOT NULL,
    FOREIGN KEY (state_id) REFERENCES State(id)
);

-- Core user tables
CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    user_type VARCHAR2(10) CHECK (user_type IN ('admin', 'student')) NOT NULL
);

CREATE TABLE Students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    student_id VARCHAR2(20) UNIQUE NOT NULL,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    cellphone VARCHAR2(20),
    house_phone VARCHAR2(20),
    career_id NUMBER NOT NULL,
    faculty_id NUMBER NOT NULL,
    campus_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (career_id) REFERENCES Career(id),
    FOREIGN KEY (faculty_id) REFERENCES Faculty(id),
    FOREIGN KEY (campus_id) REFERENCES Campus(id)
);

CREATE TABLE Admins (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    name VARCHAR2(100) NOT NULL,
    faculty_id NUMBER NOT NULL,
    campus_id NUMBER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (faculty_id) REFERENCES Faculty(id),
    FOREIGN KEY (campus_id) REFERENCES Campus(id)
);

-- Normalized personal info
CREATE TABLE PersonDetails (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apellido_paterno VARCHAR2(50),
    apellido_materno VARCHAR2(50),
    nombres VARCHAR2(100),
    fecha_nacimiento DATE,
    lugar_nacimiento VARCHAR2(100),
    sexo VARCHAR2(10),
    edad NUMBER,
    estado_civil VARCHAR2(20)
);

-- Normalized address
CREATE TABLE Address (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(100),
    numero VARCHAR2(20),
    colonia VARCHAR2(100),
    ciudad_id NUMBER,
    estado_id NUMBER,
    FOREIGN KEY (ciudad_id) REFERENCES City(id),
    FOREIGN KEY (estado_id) REFERENCES State(id)
);

-- Normalized institution info
CREATE TABLE Institution (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    departamento VARCHAR2(100),
    calle VARCHAR2(100),
    numero VARCHAR2(20),
    colonia VARCHAR2(100),
    ciudad VARCHAR2(100),
    estado VARCHAR2(100),
    telefono VARCHAR2(20),
    celular VARCHAR2(20)
);

-- Forms submitted by students
CREATE TABLE SocialServiceForms (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    person_details_id NUMBER,
    address_id NUMBER,
    institution_id NUMBER,
    telefono VARCHAR2(20),
    celular VARCHAR2(20),
    correo VARCHAR2(100),
    semestre NUMBER,
    porcentaje_materias VARCHAR2(50),
    zona VARCHAR2(10),
    horario VARCHAR2(100),
    modalidad VARCHAR2(30),
    platica_sensibilizacion VARCHAR2(3) CHECK (platica_sensibilizacion IN ('si', 'no')),
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    submitted_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (student_id) REFERENCES Students(id),
    FOREIGN KEY (person_details_id) REFERENCES PersonDetails(id),
    FOREIGN KEY (address_id) REFERENCES Address(id),
    FOREIGN KEY (institution_id) REFERENCES Institution(id)
);

-- Accepted students (subset of SocialServiceForms)
CREATE TABLE AcceptedStudents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id NUMBER UNIQUE NOT NULL,
    accepted_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (form_id) REFERENCES SocialServiceForms(id)
);

-- Progress tracking
CREATE TABLE SocialServiceProgress (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER UNIQUE NOT NULL,
    paperwork_complete CHAR(1) CHECK (paperwork_complete IN ('Y', 'N')),
    logs_complete CHAR(1) CHECK (logs_complete IN ('Y', 'N')),
    hours_completed NUMBER,
    updated_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (student_id) REFERENCES Students(id)
);

INSERT INTO Users (username, password, user_type) VALUES ('anaadm', 'admin123', 'admin');
INSERT INTO Users (username, password, user_type) VALUES ('luisadm', 'admin456', 'admin');
INSERT INTO Users (username, password, user_type) VALUES ('jose_gomez', 'pass001', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('maria_hernandez', 'pass002', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('carlos_lopez', 'pass003', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('laura_ruiz', 'pass004', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('fernando_diaz', 'pass005', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('sofia_fernandez', 'pass006', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('diego_ramirez', 'pass007', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('valeria_mendoza', 'pass008', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('david_ortiz', 'pass009', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('andrea_torres', 'pass010', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('hector_rojas', 'pass011', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('elena_castro', 'pass012', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('raul_martinez', 'pass013', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('natalia_vargas', 'pass014', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('sergio_soto', 'pass015', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('monica_guzman', 'pass016', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('jorge_sandoval', 'pass017', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('fatima_morales', 'pass018', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ricardo_salazar', 'pass019', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('karla_navarro', 'pass020', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('alejandro_rivera', 'pass021', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('diana_vega', 'pass022', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ivan_aguilar', 'pass023', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('isabel_campos', 'pass024', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('roberto_miranda', 'pass025', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('pamela_reyes', 'pass026', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('marco_ayala', 'pass027', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('alejandra_garza', 'pass028', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('adrian_pineda', 'pass029', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('melissa_luna', 'pass030', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('julio_carrillo', 'pass031', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('brenda_mendez', 'pass032', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('francisco_valdez', 'pass033', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('mariana_silva', 'pass034', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('gustavo_perez', 'pass035', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('rebeca_rios', 'pass036', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('tomas_quintero', 'pass037', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('irene_lozano', 'pass038', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('arturo_barajas', 'pass039', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('judith_molina', 'pass040', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ramiro_guerrero', 'pass041', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('paola_santos', 'pass042', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('edgar_tapia', 'pass043', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('gema_fuentes', 'pass044', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('bryan_cano', 'pass045', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('araceli_martel', 'pass046', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('lazaro_castillo', 'pass047', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('leticia_sierra', 'pass048', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('hugo_olivares', 'pass049', 'student');
INSERT INTO Users (username, password, user_type) VALUES ('ruth_saldana', 'pass050', 'student');
